export const DEMO_TRANSACTIONS = [
  {
    id: 1,
    categoryId: 'groceries',
    amount: 45.50,
    description: 'Weekly grocery run',
    tag: 'Supermarket',
    date: new Date(2026, 6, 21).toISOString(),
    whoPaid: 'Alex',
    splitType: 'one',
  },
  {
    id: 2,
    categoryId: 'going-out',
    amount: 32.00,
    description: 'Dinner at Italian place',
    tag: 'Restaurant',
    date: new Date(2026, 6, 20).toISOString(),
    whoPaid: 'Jordan',
    splitType: 'split',
  },
  {
    id: 3,
    categoryId: 'utilities',
    amount: 120.00,
    description: 'Monthly rent',
    tag: 'Rent',
    date: new Date(2026, 6, 19).toISOString(),
    whoPaid: 'Alex',
    splitType: 'split',
  },
  {
    id: 4,
    categoryId: 'subscriptions',
    amount: 14.99,
    description: 'Streaming service',
    tag: 'Streaming',
    date: new Date(2026, 6, 18).toISOString(),
    whoPaid: 'Jordan',
    splitType: 'split',
  },
  {
    id: 5,
    categoryId: 'car',
    amount: 55.00,
    description: 'Gas fill-up',
    tag: 'Fuel',
    date: new Date(2026, 6, 17).toISOString(),
    whoPaid: 'Alex',
    splitType: 'one',
  },
]
