export const CATEGORIES = [
  {
    id: 'car',
    name: 'Car',
    emoji: '🚗',
    color: '#dc2626',
    colorTw: 'cat-car',
    icon: 'car',
    description: 'Fuel, insurance, maintenance, parking, toll, tax',
    subcategories: ['Fuel', 'Insurance', 'Maintenance', 'Parking', 'Toll', 'Tax', 'Other'],
  },
  {
    id: 'subscriptions',
    name: 'Subscriptions',
    emoji: '📦',
    color: '#a855f7',
    colorTw: 'cat-subscriptions',
    icon: 'box',
    description: 'Netflix, Spotify, gym, apps, recurring services',
    subcategories: ['Streaming', 'Music', 'Gym', 'Software', 'Other'],
  },
  {
    id: 'groceries',
    name: 'Groceries',
    emoji: '🛒',
    color: '#16a34a',
    colorTw: 'cat-groceries',
    icon: 'cart',
    description: 'Supermarket runs, market, delivery',
    subcategories: ['Supermarket', 'Market', 'Delivery', 'Other'],
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    emoji: '🎉',
    color: '#eab308',
    colorTw: 'cat-entertainment',
    icon: 'star',
    description: 'Cinema, concerts, games, hobbies',
    subcategories: ['Cinema', 'Concert', 'Games', 'Hobbies', 'Other'],
  },
  {
    id: 'going-out',
    name: 'Going Out',
    emoji: '🍽️',
    color: '#ea580c',
    colorTw: 'cat-going-out',
    icon: 'utensils',
    description: 'Restaurants, bars, cafés, takeaway',
    subcategories: ['Restaurant', 'Bar', 'Café', 'Takeaway', 'Other'],
  },
  {
    id: 'utilities',
    name: 'Rent & Utilities',
    emoji: '🏠',
    color: '#0284c7',
    colorTw: 'cat-utilities',
    icon: 'home',
    description: 'Rent, electricity, gas, water, internet, phone',
    subcategories: ['Rent', 'Electricity', 'Gas', 'Water', 'Internet', 'Phone', 'Other'],
  },
  {
    id: 'home',
    name: 'Home',
    emoji: '🔧',
    color: '#14b8a6',
    colorTw: 'cat-home',
    icon: 'wrench',
    description: 'Furniture, repairs, cleaning supplies, appliances',
    subcategories: ['Furniture', 'Repairs', 'Cleaning', 'Appliances', 'Other'],
  },
  {
    id: 'other',
    name: 'Other',
    emoji: '✦',
    color: '#6b7280',
    colorTw: 'cat-other',
    icon: 'sparkles',
    description: 'Anything that does not fit',
    subcategories: ['Misc'],
  },
]

export const getCategoryById = (id) => CATEGORIES.find((cat) => cat.id === id)
export const getCategoryByName = (name) => CATEGORIES.find((cat) => cat.name === name)
